apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecofusion-deployment
  namespace: ecofusion-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecofusion
  template:
    metadata:
      labels:
        app: ecofusion
    spec:
      serviceAccountName: ecofusion-gsa@eminent-yen-429707-d4.iam.gserviceaccount.com # This should be the Kubernetes service account name
      containers:
      - name: ecofusion
        image: gcr.io/eminent-yen-429707-d4/ecofusion:latest  # Change this to use a tag instead of SHA256
        imagePullPolicy: Always
        ports:
        - containerPort: 3000